### PR TITLE
Some kind of showDelay option would be nice #59

### PR DESCRIPTION
**Pull request by mingyec**
[#59](https://github.com/ankurk91/vue-loading-overlay/issues/59)

### CODE REVIEW

**Comment by mingyec** [comment]
oh, I found that delay was misspelled

**Comment by ankurk91** [comment]
How does it work?

**Comment by mingyec** [comment]
The design pattern "dependency inversion".When displaying, create a Promise with a delay, and resolve the Promise when it is closed, so that it can be reached. I ran the test and both the component and plugin passed

**Comment by ankurk91** [comment]
Too much hacky code, i will find another easy and readable solution

**Pull request closed without merging**
